version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  order-service:
    build: ./order-service
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
